# Site settings
title: Mike Vallano | Web Developer
description: Mike's site
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mike Vallano
user_description: Ruby on Rails Developer
user_title: Web Developer
email: mikevallano@gmail.com
twitter_username: mikevallano
github_username:  mikevallano
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
